### Adicionar turma
POST http://localhost:3003/turma
Content-Type: application/json

{
    "nome": "Turma3",
    "modulo": "3"
}


### Adicionar novo estudante ou docente
POST http://localhost:3003/usuario
Content-Type: application/json

{
    "table":"docente",
    "nome":"docente2",
    "email":"docente2@email.com",
    "day":"01",
    "month":"01",
    "year":"2000",
    "turma_id":"1672255562647"
}


### Buscar estudante, docente ou turma
GET http://localhost:3003/entity
Content-Type: application/json

{
    "table":"turma",
    "nome":""
}


### Alterar turma do docente ou estudante
PUT http://localhost:3003/usuario
Content-Type: application/json

{
    "table":"estudante",
    "idUsuario":"1672255776712",
    "idNovaTurma":"1672255543718"
}


### Alterar o modulo de uma turma
PUT http://localhost:3003/turma
Content-Type: application/json

{
    "id":"1672255543718",
    "modulo":"1"
}


### Obter todos os estudantes e docentes de uma turma
GET http://localhost:3003/members?turma=1671388198312
Content-Type: application/json


### Obter estudantes com um determinado hobby
GET http://localhost:3003/estudante?idHobby=01
Content-Type: application/json